/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AnotarNotasVistaD.java
 *
 * Created on 08-ene-2012, 13:25:09
 */

package colegio_inftel;

import java.awt.event.ActionListener;
import java.awt.event.FocusListener;
import java.awt.event.KeyListener;
import java.util.ArrayList;

/**
 *
 * @author agumpg
 */
public class AnotarNotasVistaD extends javax.swing.JDialog {

    /** Creates new form AnotarNotasVistaD */
    public AnotarNotasVistaD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocationRelativeTo(null); //centramos la ventana en pantalla
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pCabecera = new javax.swing.JPanel();
        lbAlumno = new javax.swing.JLabel();
        lbAsignatura = new javax.swing.JLabel();
        lbAlumnoValue = new javax.swing.JLabel();
        lbInformaticaValue = new javax.swing.JLabel();
        lbCurso = new javax.swing.JLabel();
        lbGrupo = new javax.swing.JLabel();
        lbCursoValue = new javax.swing.JLabel();
        lbGrupoValue = new javax.swing.JLabel();
        pCuerpo = new javax.swing.JPanel();
        marcoNotas = new javax.swing.JLayeredPane();
        lbPrimera = new javax.swing.JLabel();
        lbSegunda = new javax.swing.JLabel();
        lbTercera = new javax.swing.JLabel();
        nota1 = new javax.swing.JTextField();
        nota2 = new javax.swing.JTextField();
        nota3 = new javax.swing.JTextField();
        notaFinalValue = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        notaFinal = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pCabecera.setBackground(new java.awt.Color(255, 254, 254));

        lbAlumno.setText("Alumno:");

        lbAsignatura.setText("Asignatura:");

        lbAlumnoValue.setForeground(new java.awt.Color(33, 94, 186));
        lbAlumnoValue.setText("Alfonso Pérez Sánchez");

        lbInformaticaValue.setForeground(new java.awt.Color(140, 140, 140));
        lbInformaticaValue.setText("Informática");

        lbCurso.setText("Curso:");

        lbGrupo.setText("Grupo:");

        lbCursoValue.setForeground(new java.awt.Color(140, 140, 140));
        lbCursoValue.setText("1º de E.S.0");

        lbGrupoValue.setForeground(new java.awt.Color(140, 140, 140));
        lbGrupoValue.setText("A");

        javax.swing.GroupLayout pCabeceraLayout = new javax.swing.GroupLayout(pCabecera);
        pCabecera.setLayout(pCabeceraLayout);
        pCabeceraLayout.setHorizontalGroup(
            pCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCabeceraLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbAsignatura)
                    .addComponent(lbAlumno))
                .addGap(18, 18, 18)
                .addGroup(pCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAlumnoValue)
                    .addComponent(lbInformaticaValue))
                .addGap(90, 90, 90)
                .addGroup(pCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbGrupo)
                    .addComponent(lbCurso))
                .addGap(18, 18, 18)
                .addGroup(pCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCursoValue)
                    .addComponent(lbGrupoValue))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        pCabeceraLayout.setVerticalGroup(
            pCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCabeceraLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAlumno)
                    .addComponent(lbCursoValue)
                    .addComponent(lbCurso)
                    .addComponent(lbAlumnoValue))
                .addGap(18, 18, 18)
                .addGroup(pCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAsignatura)
                    .addComponent(lbGrupoValue)
                    .addComponent(lbGrupo)
                    .addComponent(lbInformaticaValue))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        marcoNotas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbPrimera.setText("Primera Evaluación:");
        lbPrimera.setBounds(80, 30, 140, 16);
        marcoNotas.add(lbPrimera, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbSegunda.setText("Segunda Evaluación:");
        lbSegunda.setBounds(80, 60, 150, 16);
        marcoNotas.add(lbSegunda, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbTercera.setText("Tercera Evaluación:");
        lbTercera.setBounds(80, 90, 140, 16);
        marcoNotas.add(lbTercera, javax.swing.JLayeredPane.DEFAULT_LAYER);

        nota1.setForeground(new java.awt.Color(54, 98, 209));
        nota1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nota1.setText("0.0");
        nota1.setBounds(330, 30, 60, 20);
        marcoNotas.add(nota1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        nota2.setForeground(new java.awt.Color(54, 98, 209));
        nota2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nota2.setText("0.0");
        nota2.setBounds(330, 60, 60, 20);
        marcoNotas.add(nota2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        nota3.setForeground(new java.awt.Color(54, 98, 209));
        nota3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nota3.setText("0.0");
        nota3.setBounds(330, 90, 60, 20);
        marcoNotas.add(nota3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        notaFinalValue.setForeground(new java.awt.Color(145, 145, 145));
        notaFinalValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        notaFinalValue.setText("0.0");
        notaFinalValue.setBounds(330, 140, 60, 20);
        marcoNotas.add(notaFinalValue, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setText("Calificación Final:");
        jLabel1.setBounds(80, 180, 122, 16);
        marcoNotas.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        notaFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        notaFinal.setBounds(230, 170, 160, 28);
        marcoNotas.add(notaFinal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnGuardar.setText("Guardar");

        btnCerrar.setText("Cerrar");

        javax.swing.GroupLayout pCuerpoLayout = new javax.swing.GroupLayout(pCuerpo);
        pCuerpo.setLayout(pCuerpoLayout);
        pCuerpoLayout.setHorizontalGroup(
            pCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCuerpoLayout.createSequentialGroup()
                .addGroup(pCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pCuerpoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pCuerpoLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(marcoNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        pCuerpoLayout.setVerticalGroup(
            pCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(marcoNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(pCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pCabecera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AnotarNotasVistaD dialog = new AnotarNotasVistaD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbAlumno;
    private javax.swing.JLabel lbAlumnoValue;
    private javax.swing.JLabel lbAsignatura;
    private javax.swing.JLabel lbCurso;
    private javax.swing.JLabel lbCursoValue;
    private javax.swing.JLabel lbGrupo;
    private javax.swing.JLabel lbGrupoValue;
    private javax.swing.JLabel lbInformaticaValue;
    private javax.swing.JLabel lbPrimera;
    private javax.swing.JLabel lbSegunda;
    private javax.swing.JLabel lbTercera;
    private javax.swing.JLayeredPane marcoNotas;
    private javax.swing.JTextField nota1;
    private javax.swing.JTextField nota2;
    private javax.swing.JTextField nota3;
    private javax.swing.JTextField notaFinal;
    private javax.swing.JTextField notaFinalValue;
    private javax.swing.JPanel pCabecera;
    private javax.swing.JPanel pCuerpo;
    // End of variables declaration//GEN-END:variables


    public void addGuardarListener(ActionListener a){
        btnGuardar.addActionListener(a);
    }

    public void addCerrarListener(ActionListener a){
        btnCerrar.addActionListener(a);
    }

    public void addValidarNotasKeyTyped(KeyListener evt){
        nota1.addKeyListener(evt);
        nota2.addKeyListener(evt);
        nota3.addKeyListener(evt);
    }

    public void addFormatearNota(FocusListener evt  ){
        nota1.addFocusListener(evt);
        nota2.addFocusListener(evt);
        nota3.addFocusListener(evt);
    }



    public ArrayList<Double> getNotas(){
        ArrayList<Double> notas = new ArrayList<Double>();

        notas.add(getN1());
        notas.add(getN2());
        notas.add(getN3());

        return notas;
    }


    public Double getN1(){
        Double n;
        try{
            n=Double.parseDouble(nota1.getText());
        } catch (NumberFormatException e) {
            n=new Double(0.0);
        }

        return n;
    }

    public Double getN2(){
        Double n;
        try{
            n=Double.parseDouble(nota2.getText());
        } catch (NumberFormatException e) {
            n=new Double(0.0);
        }

        return n;
    }

    public Double getN3(){
        Double n;
        try{
            n=Double.parseDouble(nota3.getText());
        } catch (NumberFormatException e) {
            n=new Double(0.0);
        }

        return n;
    }


    public Double getNFinal(){
        Double n;
        try{
            n=Double.parseDouble(notaFinal.getText());
        } catch (NumberFormatException e) {
            n=new Double(0.0);
        }

        return n;
    }


    public String getNota1(){
        return nota1.getText();
    }


    public String getNota2(){
        return nota2.getText();
    }

    public String getNota3(){
        return nota3.getText();
    }

    public String getNotaFinal(){
        return notaFinal.getText();
    }

    public void setNotaFinal(String nota){
        notaFinal.setText(nota);

        notaFinalValue.setText(nota);

        if (Double.parseDouble(nota) < 5){
            notaFinal.setText("SUSPENSO");
        } else if (Double.parseDouble(nota)>=5 && Double.parseDouble(nota)<7) {
            notaFinal.setText("APROBADO");
        } else if (Double.parseDouble(nota)>=7 && Double.parseDouble(nota)<9) {
            notaFinal.setText("NOTABLE");
        } else {
            notaFinal.setText("SOBRESALIENTE");
        }

    }

    public void setNota1(String nota){
        nota1.setText(nota);
    }

    public void setNota2(String nota){
        nota2.setText(nota);
    }

    public void setNota3(String nota){
        nota3.setText(nota);
    }



}
