/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EscuelaVistaNotasIncidencias.java
 *
 * Created on 27/12/2011, 08:15:04 PM
 */

package colegio_inftel;

/**
 *
 * @author BlackCrystal™
 */
public class EscuelaVistaNotasIncidencias extends javax.swing.JFrame {

    /** Creates new form EscuelaVistaNotasIncidencias */
    public EscuelaVistaNotasIncidencias() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        trimestre1Label = new javax.swing.JLabel();
        trimestre1Text = new javax.swing.JTextField();
        trimestre2Label = new javax.swing.JLabel();
        trimestre3Label = new javax.swing.JLabel();
        trimestre2Text = new javax.swing.JTextField();
        trimestre3Text = new javax.swing.JTextField();
        apellido1NotasLabel1 = new javax.swing.JLabel();
        notaFinalText = new javax.swing.JTextField();
        notaFinalLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        faltasLabel = new javax.swing.JLabel();
        faltasText = new javax.swing.JTextField();
        retrasosLabel = new javax.swing.JLabel();
        sancionesLabel = new javax.swing.JLabel();
        retrasosText = new javax.swing.JTextField();
        sancionesText = new javax.swing.JTextField();
        apellido1NotasLabel4 = new javax.swing.JLabel();
        comentariosLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        comentariosTextArea = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        confirmarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        expedienteLabel = new javax.swing.JLabel();
        cursoLabel = new javax.swing.JLabel();
        nombreProfesorLabel = new javax.swing.JLabel();
        cursoValorLabel = new javax.swing.JLabel();
        alumnoLabel = new javax.swing.JLabel();
        asignaturaLabel = new javax.swing.JLabel();
        grupoLabel = new javax.swing.JLabel();
        expedienteValorLabel = new javax.swing.JLabel();
        grupoValorLabel = new javax.swing.JLabel();
        nombreAlumnoLabel = new javax.swing.JLabel();
        valorAnyoEscolarLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escuela 2.0 -- Sistema de Gestión de Alumnos");

        trimestre1Label.setText("1er Trimestre");
        trimestre1Label.setName("trimestre1Label"); // NOI18N

        trimestre1Text.setName("trimestre1Text"); // NOI18N

        trimestre2Label.setText("2º Trimestre");
        trimestre2Label.setName("trimestre2Label"); // NOI18N

        trimestre3Label.setText("3er Trimestre");
        trimestre3Label.setName("trimestre3Label"); // NOI18N

        trimestre2Text.setName("trimestre2Text"); // NOI18N

        trimestre3Text.setName("trimestre3Text"); // NOI18N

        apellido1NotasLabel1.setName("apellido1Label"); // NOI18N

        notaFinalText.setName("notaFinalText"); // NOI18N

        notaFinalLabel.setText("Nota Final");
        notaFinalLabel.setName("notaFinalLabel"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trimestre1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trimestre1Label))
                .addGap(81, 81, 81)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notaFinalLabel)
                    .addComponent(notaFinalText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(trimestre2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trimestre2Label))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(apellido1NotasLabel1))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(trimestre3Label)
                                    .addComponent(trimestre3Text, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(52, 52, 52))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trimestre1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trimestre2Label)
                    .addComponent(trimestre3Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trimestre1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trimestre2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trimestre3Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(apellido1NotasLabel1)
                    .addComponent(notaFinalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(notaFinalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Calificaciones", jPanel1);

        faltasLabel.setText("Faltas");
        faltasLabel.setName("faltasLabel"); // NOI18N

        faltasText.setName("faltasText"); // NOI18N

        retrasosLabel.setText("Retrasos");
        retrasosLabel.setName("retrasosLabel"); // NOI18N

        sancionesLabel.setText("Sanciones");
        sancionesLabel.setName("sancionesLabel"); // NOI18N

        retrasosText.setName("retrasosText"); // NOI18N

        sancionesText.setName("sancionesText"); // NOI18N

        apellido1NotasLabel4.setName("apellido1Label"); // NOI18N

        comentariosLabel.setText("Comentarios");
        comentariosLabel.setName("comentariosLabel"); // NOI18N

        comentariosTextArea.setColumns(20);
        comentariosTextArea.setRows(5);
        comentariosTextArea.setName("comentariosTextArea"); // NOI18N
        jScrollPane1.setViewportView(comentariosTextArea);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(apellido1NotasLabel4))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(faltasText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(faltasLabel))
                                .addGap(134, 134, 134)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(retrasosText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(retrasosLabel))
                                .addGap(118, 118, 118)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sancionesLabel)
                                    .addComponent(sancionesText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(comentariosLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(faltasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retrasosLabel)
                    .addComponent(sancionesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(faltasText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retrasosText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sancionesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apellido1NotasLabel4)
                    .addComponent(comentariosLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Incidencias", jPanel2);

        confirmarButton.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        confirmarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/colegio_inftel/Imagenes/boton_confirmar.JPG"))); // NOI18N
        confirmarButton.setContentAreaFilled(false);
        confirmarButton.setName("confirmarButton"); // NOI18N

        cancelarButton.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        cancelarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/colegio_inftel/Imagenes/boton_cancelar.JPG"))); // NOI18N
        cancelarButton.setContentAreaFilled(false);
        cancelarButton.setName("cancelarButton"); // NOI18N
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addComponent(confirmarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelarButton)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelarButton)
                    .addComponent(confirmarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 153));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        expedienteLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        expedienteLabel.setText("Expediente:");
        expedienteLabel.setName("expedienteLabel"); // NOI18N

        cursoLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        cursoLabel.setText("Curso:");
        cursoLabel.setName("cursoLabel"); // NOI18N

        nombreProfesorLabel.setFont(new java.awt.Font("Tahoma", 2, 11));
        nombreProfesorLabel.setName("nombreProfesorLabel"); // NOI18N

        cursoValorLabel.setFont(new java.awt.Font("Tahoma", 2, 11));
        cursoValorLabel.setText("4º de ESO");
        cursoValorLabel.setName("cursoValorLabel"); // NOI18N

        alumnoLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        alumnoLabel.setText("Alumno:");
        alumnoLabel.setName("alumnoLabel"); // NOI18N

        asignaturaLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        asignaturaLabel.setText("Asignatura:");
        asignaturaLabel.setName("asignaturaLabel"); // NOI18N

        grupoLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        grupoLabel.setText("Grupo:");
        grupoLabel.setName("grupoLabel"); // NOI18N

        expedienteValorLabel.setFont(new java.awt.Font("Tahoma", 2, 11));
        expedienteValorLabel.setText("0001/2011");
        expedienteValorLabel.setName("expedienteValorLabel"); // NOI18N

        grupoValorLabel.setFont(new java.awt.Font("Tahoma", 2, 11));
        grupoValorLabel.setText("A");
        grupoValorLabel.setName("grupoValorLabel"); // NOI18N

        nombreAlumnoLabel.setFont(new java.awt.Font("Tahoma", 2, 11));
        nombreAlumnoLabel.setText("Alfonso Pérez Pérez");
        nombreAlumnoLabel.setName("nombreAlumnoLabel"); // NOI18N

        valorAnyoEscolarLabel4.setFont(new java.awt.Font("Tahoma", 2, 11));
        valorAnyoEscolarLabel4.setText("Matemáticas");
        valorAnyoEscolarLabel4.setName("ano_escolarLabel"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(alumnoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(nombreAlumnoLabel))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(asignaturaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(valorAnyoEscolarLabel4)))
                .addGap(148, 148, 148)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cursoLabel)
                            .addComponent(grupoLabel))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nombreProfesorLabel)
                            .addComponent(cursoValorLabel)
                            .addComponent(grupoValorLabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(expedienteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(expedienteValorLabel)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreProfesorLabel)
                    .addComponent(alumnoLabel)
                    .addComponent(nombreAlumnoLabel)
                    .addComponent(expedienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expedienteValorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asignaturaLabel)
                    .addComponent(cursoValorLabel)
                    .addComponent(valorAnyoEscolarLabel4)
                    .addComponent(cursoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grupoValorLabel)
                    .addComponent(grupoLabel))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(36, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cancelarButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscuelaVistaNotasIncidencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alumnoLabel;
    private javax.swing.JLabel apellido1NotasLabel1;
    private javax.swing.JLabel apellido1NotasLabel4;
    private javax.swing.JLabel asignaturaLabel;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel comentariosLabel;
    private javax.swing.JTextArea comentariosTextArea;
    private javax.swing.JButton confirmarButton;
    private javax.swing.JLabel cursoLabel;
    private javax.swing.JLabel cursoValorLabel;
    private javax.swing.JLabel expedienteLabel;
    private javax.swing.JLabel expedienteValorLabel;
    private javax.swing.JLabel faltasLabel;
    private javax.swing.JTextField faltasText;
    private javax.swing.JLabel grupoLabel;
    private javax.swing.JLabel grupoValorLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel nombreAlumnoLabel;
    private javax.swing.JLabel nombreProfesorLabel;
    private javax.swing.JLabel notaFinalLabel;
    private javax.swing.JTextField notaFinalText;
    private javax.swing.JLabel retrasosLabel;
    private javax.swing.JTextField retrasosText;
    private javax.swing.JLabel sancionesLabel;
    private javax.swing.JTextField sancionesText;
    private javax.swing.JLabel trimestre1Label;
    private javax.swing.JTextField trimestre1Text;
    private javax.swing.JLabel trimestre2Label;
    private javax.swing.JTextField trimestre2Text;
    private javax.swing.JLabel trimestre3Label;
    private javax.swing.JTextField trimestre3Text;
    private javax.swing.JLabel valorAnyoEscolarLabel4;
    // End of variables declaration//GEN-END:variables

}
