/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EscuelaVistaIncidencias.java
 *
 * Created on 2/01/2012, 09:18:33 PM
 */

package colegio_inftel;

import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author BlackCrystal™
 */
public class EscuelaVistaIncidencias extends javax.swing.JFrame {

    private EscuelaModeloIncidencias modelo;
    /** Creates new form EscuelaVistaIncidencias */
    public EscuelaVistaIncidencias(EscuelaModeloIncidencias modelo) {
        this.modelo=modelo;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaIncidencias = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        expedienteLabel = new javax.swing.JLabel();
        cursoLabel = new javax.swing.JLabel();
        nombreProfesorLabel = new javax.swing.JLabel();
        cursoValorLabel = new javax.swing.JLabel();
        alumnoLabel = new javax.swing.JLabel();
        asignaturaLabel = new javax.swing.JLabel();
        grupoLabel = new javax.swing.JLabel();
        expedienteValorLabel = new javax.swing.JLabel();
        grupoValorLabel = new javax.swing.JLabel();
        nombreAlumnoLabel = new javax.swing.JLabel();
        asignaturaValorLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        cursoLabel1 = new javax.swing.JLabel();
        nombreProfesorLabel1 = new javax.swing.JLabel();
        cursoValorLabel1 = new javax.swing.JLabel();
        alumnoLabel1 = new javax.swing.JLabel();
        asignaturaLabel1 = new javax.swing.JLabel();
        grupoLabel1 = new javax.swing.JLabel();
        grupoValorLabel1 = new javax.swing.JLabel();
        nombreAlumnoLabel1 = new javax.swing.JLabel();
        asignaturaValorLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        faltasLabel = new javax.swing.JLabel();
        faltasText = new javax.swing.JTextField();
        retrasosLabel = new javax.swing.JLabel();
        sancionesLabel = new javax.swing.JLabel();
        retrasosText = new javax.swing.JTextField();
        sancionesText = new javax.swing.JTextField();
        apellido1NotasLabel4 = new javax.swing.JLabel();
        comentariosLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        comentariosTextArea = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        confirmarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();

        ventanaIncidencias.setTitle("Escuela2.0 --Incidencias ");
        ventanaIncidencias.setName("ventanaIncidencias"); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 153));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        expedienteLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        expedienteLabel.setText("Expediente:");
        expedienteLabel.setName("expedienteLabel"); // NOI18N

        cursoLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        cursoLabel.setText("Curso:");
        cursoLabel.setName("cursoLabel"); // NOI18N

        nombreProfesorLabel.setFont(new java.awt.Font("Tahoma", 2, 11));
        nombreProfesorLabel.setName("nombreProfesorLabel"); // NOI18N

        cursoValorLabel.setFont(new java.awt.Font("Tahoma", 2, 11));
        cursoValorLabel.setText("4º de ESO");
        cursoValorLabel.setName("cursoValorLabel"); // NOI18N

        alumnoLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        alumnoLabel.setText("Alumno:");
        alumnoLabel.setName("alumnoLabel"); // NOI18N

        asignaturaLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        asignaturaLabel.setText("Asignatura:");
        asignaturaLabel.setName("asignaturaLabel"); // NOI18N

        grupoLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        grupoLabel.setText("Grupo:");
        grupoLabel.setName("grupoLabel"); // NOI18N

        expedienteValorLabel.setFont(new java.awt.Font("Tahoma", 2, 11));
        expedienteValorLabel.setText("0001/2011");
        expedienteValorLabel.setName("expedienteValorLabel"); // NOI18N

        grupoValorLabel.setFont(new java.awt.Font("Tahoma", 2, 11));
        grupoValorLabel.setText("A");
        grupoValorLabel.setName("grupoValorLabel"); // NOI18N

        nombreAlumnoLabel.setFont(new java.awt.Font("Tahoma", 2, 11));
        nombreAlumnoLabel.setText("Alfonso Pérez Pérez");
        nombreAlumnoLabel.setName("nombreAlumnoLabel"); // NOI18N

        asignaturaValorLabel.setFont(new java.awt.Font("Tahoma", 2, 11));
        asignaturaValorLabel.setText("Matemáticas");
        asignaturaValorLabel.setName("asignaturaValorLabel"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(alumnoLabel)
                                .addGap(18, 18, 18)
                                .addComponent(nombreAlumnoLabel))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(asignaturaLabel)
                                .addGap(18, 18, 18)
                                .addComponent(asignaturaValorLabel)))
                        .addGap(117, 117, 117)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(expedienteLabel)
                            .addComponent(cursoLabel)))
                    .addComponent(grupoLabel))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(nombreProfesorLabel))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cursoValorLabel)
                            .addComponent(expedienteValorLabel)
                            .addComponent(grupoValorLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreProfesorLabel)
                    .addComponent(alumnoLabel)
                    .addComponent(nombreAlumnoLabel)
                    .addComponent(expedienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expedienteValorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asignaturaLabel)
                    .addComponent(asignaturaValorLabel)
                    .addComponent(cursoLabel)
                    .addComponent(cursoValorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grupoLabel)
                    .addComponent(grupoValorLabel))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ventanaIncidenciasLayout = new javax.swing.GroupLayout(ventanaIncidencias.getContentPane());
        ventanaIncidencias.getContentPane().setLayout(ventanaIncidenciasLayout);
        ventanaIncidenciasLayout.setHorizontalGroup(
            ventanaIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaIncidenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ventanaIncidenciasLayout.setVerticalGroup(
            ventanaIncidenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaIncidenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(348, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escuela2.0 -- Incidencias");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cursoLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cursoLabel1.setText("Curso:");
        cursoLabel1.setName("cursoLabel"); // NOI18N

        nombreProfesorLabel1.setFont(new java.awt.Font("Tahoma", 2, 11));
        nombreProfesorLabel1.setName("nombreProfesorLabel"); // NOI18N

        cursoValorLabel1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        cursoValorLabel1.setText("4º de ESO");
        cursoValorLabel1.setName("cursoValorLabel"); // NOI18N

        alumnoLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        alumnoLabel1.setText("Alumno:");
        alumnoLabel1.setName("alumnoLabel"); // NOI18N

        asignaturaLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        asignaturaLabel1.setText("Asignatura:");
        asignaturaLabel1.setName("asignaturaLabel"); // NOI18N

        grupoLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        grupoLabel1.setText("Grupo:");
        grupoLabel1.setName("grupoLabel"); // NOI18N

        grupoValorLabel1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        grupoValorLabel1.setText("A");
        grupoValorLabel1.setName("grupoValorLabel"); // NOI18N

        nombreAlumnoLabel1.setFont(new java.awt.Font("Tahoma", 2, 11));
        nombreAlumnoLabel1.setText("Alfonso Pérez Pérez");
        nombreAlumnoLabel1.setName("nombreAlumnoLabel"); // NOI18N

        asignaturaValorLabel1.setFont(new java.awt.Font("Tahoma", 2, 11));
        asignaturaValorLabel1.setText("Matemáticas");
        asignaturaValorLabel1.setName("asignaturaValorLabel"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(alumnoLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(nombreAlumnoLabel1)
                        .addGap(148, 148, 148)
                        .addComponent(cursoLabel1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(asignaturaLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(asignaturaValorLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(grupoLabel1)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(nombreProfesorLabel1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(grupoValorLabel1)
                            .addComponent(cursoValorLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreProfesorLabel1)
                    .addComponent(alumnoLabel1)
                    .addComponent(nombreAlumnoLabel1)
                    .addComponent(cursoLabel1)
                    .addComponent(cursoValorLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asignaturaLabel1)
                    .addComponent(asignaturaValorLabel1)
                    .addComponent(grupoLabel1)
                    .addComponent(grupoValorLabel1))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        faltasLabel.setText("Faltas");
        faltasLabel.setName("faltasLabel"); // NOI18N

        faltasText.setName("faltasText"); // NOI18N

        retrasosLabel.setText("Retrasos");
        retrasosLabel.setName("retrasosLabel"); // NOI18N

        sancionesLabel.setText("Sanciones");
        sancionesLabel.setName("sancionesLabel"); // NOI18N

        retrasosText.setName("retrasosText"); // NOI18N

        sancionesText.setName("sancionesText"); // NOI18N

        apellido1NotasLabel4.setName("apellido1Label"); // NOI18N

        comentariosLabel.setText("Comentarios");
        comentariosLabel.setName("comentariosLabel"); // NOI18N

        comentariosTextArea.setColumns(20);
        comentariosTextArea.setRows(5);
        comentariosTextArea.setName("comentariosTextArea"); // NOI18N
        jScrollPane1.setViewportView(comentariosTextArea);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(apellido1NotasLabel4))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(faltasText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(faltasLabel))
                                .addGap(134, 134, 134)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(retrasosText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(retrasosLabel))
                                .addGap(118, 118, 118)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sancionesLabel)
                                    .addComponent(sancionesText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(comentariosLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(faltasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retrasosLabel)
                    .addComponent(sancionesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(faltasText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retrasosText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sancionesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apellido1NotasLabel4)
                    .addComponent(comentariosLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        confirmarButton.setFont(new java.awt.Font("Tahoma", 3, 11));
        confirmarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/colegio_inftel/Imagenes/boton_confirmar.JPG"))); // NOI18N
        confirmarButton.setContentAreaFilled(false);
        confirmarButton.setName("confirmarButton"); // NOI18N

        cancelarButton.setFont(new java.awt.Font("Tahoma", 3, 11));
        cancelarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/colegio_inftel/Imagenes/boton_cancelar.JPG"))); // NOI18N
        cancelarButton.setContentAreaFilled(false);
        cancelarButton.setName("cancelarButton"); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(270, Short.MAX_VALUE)
                .addComponent(confirmarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelarButton)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelarButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(confirmarButton, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, 0, 456, Short.MAX_VALUE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alumnoLabel;
    private javax.swing.JLabel alumnoLabel1;
    private javax.swing.JLabel apellido1NotasLabel4;
    private javax.swing.JLabel asignaturaLabel;
    private javax.swing.JLabel asignaturaLabel1;
    private javax.swing.JLabel asignaturaValorLabel;
    private javax.swing.JLabel asignaturaValorLabel1;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel comentariosLabel;
    private javax.swing.JTextArea comentariosTextArea;
    private javax.swing.JButton confirmarButton;
    private javax.swing.JLabel cursoLabel;
    private javax.swing.JLabel cursoLabel1;
    private javax.swing.JLabel cursoValorLabel;
    private javax.swing.JLabel cursoValorLabel1;
    private javax.swing.JLabel expedienteLabel;
    private javax.swing.JLabel expedienteValorLabel;
    private javax.swing.JLabel faltasLabel;
    private javax.swing.JTextField faltasText;
    private javax.swing.JLabel grupoLabel;
    private javax.swing.JLabel grupoLabel1;
    private javax.swing.JLabel grupoValorLabel;
    private javax.swing.JLabel grupoValorLabel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreAlumnoLabel;
    private javax.swing.JLabel nombreAlumnoLabel1;
    private javax.swing.JLabel nombreProfesorLabel;
    private javax.swing.JLabel nombreProfesorLabel1;
    private javax.swing.JLabel retrasosLabel;
    private javax.swing.JTextField retrasosText;
    private javax.swing.JLabel sancionesLabel;
    private javax.swing.JTextField sancionesText;
    private javax.swing.JFrame ventanaIncidencias;
    // End of variables declaration//GEN-END:variables

    public void setNombreAlumno(String alumno){
        nombreAlumnoLabel.setText(alumno);
    }
    public void setAsignatura(String asignatura){
        asignaturaValorLabel.setText(asignatura);
    }
    public void setCurso(String curso){
        cursoValorLabel.setText(curso);
    }
    public void setGrupo(String grupo){
        grupoValorLabel.setText(grupo);
    }
    public int getFaltas(){
        return new Integer(faltasText.getText());
    }
    public int getRetrasos(){
        return new Integer(retrasosText.getText());
    }
    public int getSanciones(){
        return new Integer(sancionesText.getText());
    }
    public String getComentarios(){
        return new String(comentariosTextArea.getText());
    }
    public void setFaltas(int faltas){
        faltasText.setText(new Integer(faltas).toString());
    }
    public void setRetrasos(int retrasos){
        retrasosText.setText(new Integer(retrasos).toString() );
    }
    public void setSanciones(int sanciones){
        sancionesText.setText(new Integer(sanciones).toString());
    }
    public void addConfirmarListener(ActionListener a){
        confirmarButton.addActionListener(a);
        
    }
    public void addCancelarListener(ActionListener a){
        cancelarButton.addActionListener(a);
    }
  
}
