/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AnotarNotasVista.java
 *
 * Created on 04-ene-2012, 20:44:42
 */

package colegio_inftel;

import java.awt.event.ActionListener;

/**
 *
 * @author agumpg
 */
public class AnotarNotasVista extends javax.swing.JFrame {

    /** Creates new form AnotarNotasVista */
    public AnotarNotasVista() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lbAlumno = new javax.swing.JLabel();
        lbAsignatura = new javax.swing.JLabel();
        lbAsignaturaValue = new javax.swing.JLabel();
        lbCurso = new javax.swing.JLabel();
        lbGrupo = new javax.swing.JLabel();
        lbCursoValue = new javax.swing.JLabel();
        lbGrupoValue = new javax.swing.JLabel();
        lbAlumnoValue = new javax.swing.JLabel();
        pnlBody = new javax.swing.JPanel();
        marcoNotas = new javax.swing.JLayeredPane();
        lbPrimera = new javax.swing.JLabel();
        txtPrimera = new javax.swing.JTextField();
        lbSegunda = new javax.swing.JLabel();
        txtSegunda = new javax.swing.JTextField();
        lbTercera = new javax.swing.JLabel();
        txtTercera = new javax.swing.JTextField();
        lbNotaFinal = new javax.swing.JLabel();
        txNotaFinal = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calificaciones");

        pnlHeader.setBackground(java.awt.SystemColor.control);

        lbAlumno.setText("Alumno:");

        lbAsignatura.setText("Asignatura:");

        lbAsignaturaValue.setForeground(java.awt.SystemColor.textInactiveText);
        lbAsignaturaValue.setText("Informática");

        lbCurso.setText("Curso:");

        lbGrupo.setText("Grupo:");

        lbCursoValue.setForeground(java.awt.SystemColor.textInactiveText);
        lbCursoValue.setText("1º de E.S.O");

        lbGrupoValue.setForeground(java.awt.SystemColor.textInactiveText);
        lbGrupoValue.setText("B");

        lbAlumnoValue.setForeground(java.awt.SystemColor.controlHighlight);
        lbAlumnoValue.setText("Alfonso Pérez Sánchez");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAlumno)
                    .addComponent(lbAsignatura))
                .addGap(18, 18, 18)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAlumnoValue)
                    .addComponent(lbAsignaturaValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCurso)
                    .addComponent(lbGrupo))
                .addGap(18, 18, 18)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCursoValue)
                    .addComponent(lbGrupoValue))
                .addGap(72, 72, 72))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAlumno)
                            .addComponent(lbCurso)
                            .addComponent(lbCursoValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAsignatura)
                            .addComponent(lbGrupo)
                            .addComponent(lbGrupoValue)
                            .addComponent(lbAsignaturaValue)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                        .addComponent(lbAlumnoValue)
                        .addGap(28, 28, 28)))
                .addGap(20, 20, 20))
        );

        marcoNotas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbPrimera.setText("Primera Evaluación:");
        lbPrimera.setBounds(60, 20, -1, -1);
        marcoNotas.add(lbPrimera, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtPrimera.setForeground(java.awt.SystemColor.controlHighlight);
        txtPrimera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrimera.setText("1");
        txtPrimera.setBounds(300, 10, 42, -1);
        marcoNotas.add(txtPrimera, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbSegunda.setText("Segunda Evaluación:");
        lbSegunda.setBounds(60, 50, -1, -1);
        marcoNotas.add(lbSegunda, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtSegunda.setForeground(java.awt.SystemColor.controlHighlight);
        txtSegunda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSegunda.setText("7,5");
        txtSegunda.setPreferredSize(new java.awt.Dimension(22, 28));
        txtSegunda.setBounds(300, 40, 42, -1);
        marcoNotas.add(txtSegunda, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbTercera.setText("Tercera Evaluación:");
        lbTercera.setBounds(60, 80, -1, -1);
        marcoNotas.add(lbTercera, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtTercera.setForeground(java.awt.SystemColor.controlHighlight);
        txtTercera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTercera.setText("10");
        txtTercera.setPreferredSize(new java.awt.Dimension(22, 28));
        txtTercera.setBounds(300, 70, 42, -1);
        marcoNotas.add(txtTercera, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbNotaFinal.setText("Calificación Final:");

        txNotaFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txNotaFinal.setText("9");
        txNotaFinal.setEnabled(false);

        javax.swing.GroupLayout pnlBodyLayout = new javax.swing.GroupLayout(pnlBody);
        pnlBody.setLayout(pnlBodyLayout);
        pnlBodyLayout.setHorizontalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(lbNotaFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(txNotaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(marcoNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        pnlBodyLayout.setVerticalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(marcoNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNotaFinal)
                    .addComponent(txNotaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.setMaximumSize(new java.awt.Dimension(90, 29));
        btnGuardar.setMinimumSize(new java.awt.Dimension(90, 29));

        btnCerrar.setText("Cerrar");
        btnCerrar.setMaximumSize(new java.awt.Dimension(90, 29));
        btnCerrar.setMinimumSize(new java.awt.Dimension(90, 29));
        btnCerrar.setPreferredSize(new java.awt.Dimension(90, 29));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
            .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnotarNotasVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lbAlumno;
    private javax.swing.JLabel lbAlumnoValue;
    private javax.swing.JLabel lbAsignatura;
    private javax.swing.JLabel lbAsignaturaValue;
    private javax.swing.JLabel lbCurso;
    private javax.swing.JLabel lbCursoValue;
    private javax.swing.JLabel lbGrupo;
    private javax.swing.JLabel lbGrupoValue;
    private javax.swing.JLabel lbNotaFinal;
    private javax.swing.JLabel lbPrimera;
    private javax.swing.JLabel lbSegunda;
    private javax.swing.JLabel lbTercera;
    private javax.swing.JLayeredPane marcoNotas;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JTextField txNotaFinal;
    private javax.swing.JTextField txtPrimera;
    private javax.swing.JTextField txtSegunda;
    private javax.swing.JTextField txtTercera;
    // End of variables declaration//GEN-END:variables


    public void addGuardarListener(ActionListener a){
        btnGuardar.addActionListener(a);
    }

    public void addCerrarListener(ActionListener a){
        btnCerrar.addActionListener(a);
    }


}
