/*
 * AnotarNotasVista.java
 *
 * Created on 04-ene-2012, 20:44:42
 */

package colegio_inftel;

import java.awt.event.ActionListener;
import java.awt.event.KeyListener;

/**
 *
 * @author agumpg
 */
public class AnotarNotasVista extends javax.swing.JFrame {

    private AnotarNotasModelo m_modelo;

    /** Creates new form AnotarNotasVista */
    AnotarNotasVista(AnotarNotasModelo modelo) {
        m_modelo = modelo;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lbAlumno = new javax.swing.JLabel();
        lbAsignatura = new javax.swing.JLabel();
        lbAsignaturaValue = new javax.swing.JLabel();
        lbCurso = new javax.swing.JLabel();
        lbGrupo = new javax.swing.JLabel();
        lbCursoValue = new javax.swing.JLabel();
        lbGrupoValue = new javax.swing.JLabel();
        lbAlumnoValue = new javax.swing.JLabel();
        pnlBody = new javax.swing.JPanel();
        notaFinal = new javax.swing.JTextField();
        marcoNotas = new javax.swing.JLayeredPane();
        lbSegunda = new javax.swing.JLabel();
        nota1 = new javax.swing.JTextField();
        nota2 = new javax.swing.JTextField();
        lbTercera = new javax.swing.JLabel();
        nota3 = new javax.swing.JTextField();
        lbPrimera = new javax.swing.JLabel();
        lbNotaFinal = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calificaciones");
        setResizable(false);

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));

        lbAlumno.setFont(new java.awt.Font("Tahoma", 1, 11));
        lbAlumno.setForeground(new java.awt.Color(102, 102, 102));
        lbAlumno.setText("Alumno:");

        lbAsignatura.setFont(new java.awt.Font("Tahoma", 1, 11));
        lbAsignatura.setForeground(new java.awt.Color(102, 102, 102));
        lbAsignatura.setText("Asignatura:");

        lbAsignaturaValue.setForeground(new java.awt.Color(102, 102, 102));
        lbAsignaturaValue.setText("Informática");

        lbCurso.setFont(new java.awt.Font("Tahoma", 1, 11));
        lbCurso.setForeground(new java.awt.Color(102, 102, 102));
        lbCurso.setText("Curso:");

        lbGrupo.setFont(new java.awt.Font("Tahoma", 1, 11));
        lbGrupo.setForeground(new java.awt.Color(102, 102, 102));
        lbGrupo.setText("Grupo:");

        lbCursoValue.setForeground(new java.awt.Color(102, 102, 102));
        lbCursoValue.setText("1º de E.S.O");

        lbGrupoValue.setForeground(new java.awt.Color(102, 102, 102));
        lbGrupoValue.setText("B");

        lbAlumnoValue.setForeground(new java.awt.Color(33, 94, 186));
        lbAlumnoValue.setText("Alfonso Pérez Sánchez");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAlumno)
                    .addComponent(lbAsignatura))
                .addGap(18, 18, 18)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAlumnoValue)
                    .addComponent(lbAsignaturaValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCurso)
                    .addComponent(lbGrupo))
                .addGap(18, 18, 18)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCursoValue)
                    .addComponent(lbGrupoValue))
                .addGap(72, 72, 72))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAlumno)
                            .addComponent(lbCurso)
                            .addComponent(lbCursoValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAsignatura)
                            .addComponent(lbGrupo)
                            .addComponent(lbGrupoValue)
                            .addComponent(lbAsignaturaValue)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                        .addComponent(lbAlumnoValue)
                        .addGap(28, 28, 28)))
                .addGap(20, 20, 20))
        );

        notaFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        notaFinal.setText("9");

        marcoNotas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbSegunda.setText("Segunda Evaluación:");
        lbSegunda.setBounds(60, 50, 210, 16);
        marcoNotas.add(lbSegunda, javax.swing.JLayeredPane.DEFAULT_LAYER);

        nota1.setForeground(new java.awt.Color(54, 98, 209));
        nota1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nota1.setBounds(280, 20, 60, 20);
        marcoNotas.add(nota1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        nota2.setForeground(new java.awt.Color(54, 98, 209));
        nota2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nota2.setPreferredSize(new java.awt.Dimension(22, 28));
        nota2.setBounds(280, 50, 60, 20);
        marcoNotas.add(nota2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbTercera.setText("Tercera Evaluación:");
        lbTercera.setBounds(60, 80, 210, 16);
        marcoNotas.add(lbTercera, javax.swing.JLayeredPane.DEFAULT_LAYER);

        nota3.setForeground(new java.awt.Color(54, 98, 209));
        nota3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nota3.setBounds(280, 80, 60, 20);
        marcoNotas.add(nota3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbPrimera.setText("Primera Evaluación:");
        lbPrimera.setBounds(60, 20, 210, 16);
        marcoNotas.add(lbPrimera, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbNotaFinal.setText("Calificación Final:");

        javax.swing.GroupLayout pnlBodyLayout = new javax.swing.GroupLayout(pnlBody);
        pnlBody.setLayout(pnlBodyLayout);
        pnlBodyLayout.setHorizontalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createSequentialGroup()
                        .addComponent(marcoNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createSequentialGroup()
                        .addComponent(lbNotaFinal)
                        .addGap(104, 104, 104)
                        .addComponent(notaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
        );
        pnlBodyLayout.setVerticalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addComponent(marcoNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNotaFinal))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.setMaximumSize(new java.awt.Dimension(90, 29));
        btnGuardar.setMinimumSize(new java.awt.Dimension(90, 29));

        btnCerrar.setText("Cerrar");
        btnCerrar.setMaximumSize(new java.awt.Dimension(90, 29));
        btnCerrar.setMinimumSize(new java.awt.Dimension(90, 29));
        btnCerrar.setPreferredSize(new java.awt.Dimension(90, 29));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlBody, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(325, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lbAlumno;
    private javax.swing.JLabel lbAlumnoValue;
    private javax.swing.JLabel lbAsignatura;
    private javax.swing.JLabel lbAsignaturaValue;
    private javax.swing.JLabel lbCurso;
    private javax.swing.JLabel lbCursoValue;
    private javax.swing.JLabel lbGrupo;
    private javax.swing.JLabel lbGrupoValue;
    private javax.swing.JLabel lbNotaFinal;
    private javax.swing.JLabel lbPrimera;
    private javax.swing.JLabel lbSegunda;
    private javax.swing.JLabel lbTercera;
    private javax.swing.JLayeredPane marcoNotas;
    protected javax.swing.JTextField nota1;
    protected javax.swing.JTextField nota2;
    protected javax.swing.JTextField nota3;
    private javax.swing.JTextField notaFinal;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlHeader;
    // End of variables declaration//GEN-END:variables


    public void addGuardarListener(ActionListener a){
        btnGuardar.addActionListener(a);
    }

    public void addCerrarListener(ActionListener a){
        btnCerrar.addActionListener(a);
    }

    public void addValidarNotasKeyTyped(KeyListener evt){
        nota1.addKeyListener(evt);
        nota2.addKeyListener(evt);
        nota3.addKeyListener(evt);
    }


    public String getNota1(){
        return nota1.getText();
    }

    public String getNota2(){
        return nota2.getText();
    }

    public String getNota3(){
        return nota3.getText();
    }
}